<a href="https://colab.research.google.com/github/Nagasrineelamshetty/AIML-self-paced-learning-/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import sys

In [16]:
a= np.array([1,2,3],dtype='int64')
a

array([1, 2, 3])

In [5]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
#Get Dimensions
print(a.ndim)
print(b.ndim)

1
2


In [17]:
#Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [18]:
#Get Type
print(a.dtype)
print(b.dtype)

int64
float64


In [19]:
#Item size
print(a.itemsize)
print(b.itemsize)

8
8


In [20]:
#Get Total Size
print(a.size*a.itemsize)
print(a.nbytes)

24
24


#Accessing Elements


In [23]:
a=np.array([[1,2,3,4,5,6,],[8,9,10,11,12,13,]])
print(a)

[[ 1  2  3  4  5  6]
 [ 8  9 10 11 12 13]]


In [25]:
#Get a specific element
print(a[1,5])
print(a[1,-1])

13
13


In [26]:
#Get a specific row
print(a[0,:])

[1 2 3 4 5 6]


In [27]:
#Get a specific column
print(a[:,2])

[ 3 10]


In [32]:
#Getting a little more fnacy [startindex:endindex:stepsize]
print(a[0,1:6:2])
print(a[0,1:-1:2])

[2 4 6]
[2 4]


In [35]:
a[1,5]=20
print(a)
a[:,2]=[1,2]
print(a)

[[ 1  2  5  4  5  6]
 [ 8  9  5 11 12 20]]
[[ 1  2  1  4  5  6]
 [ 8  9  2 11 12 20]]


In [40]:
#3-D Example
b=np.array([[[1,2],[3,4]],[[5,6],[9,10]]])
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 9 10]]]


In [41]:
#Get Specific element
print(b[0,1,1])

4


In [43]:
print(b[:,0,:])

[[1 2]
 [5 6]]


In [46]:
b[:,1,:]=[[9,9,],[9,9,]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [9 9]]]


#Initializing different types of Arrays

In [51]:
#All zeros Matrux
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [52]:
#All ones
np.ones((4,3,2),dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [55]:
#Any other number
np.full((3,3),99,dtype='float32')

array([[99., 99., 99.],
       [99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [57]:
#Any other number(full_like)
np.full_like(a,4)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [58]:
#Random decimal numbers
np.random.rand(9,9)

array([[0.92560738, 0.78113184, 0.63491633, 0.30811285, 0.28143282,
        0.70374308, 0.79926756, 0.44603488, 0.77002773],
       [0.37196557, 0.87085997, 0.15367611, 0.76790212, 0.4085197 ,
        0.69256209, 0.82840041, 0.28056811, 0.86036494],
       [0.16720401, 0.0511342 , 0.3243375 , 0.67549382, 0.60197797,
        0.14520574, 0.20043385, 0.92013658, 0.70253696],
       [0.82973389, 0.87157463, 0.07638011, 0.37437873, 0.62787528,
        0.78499536, 0.92249846, 0.79701126, 0.29771671],
       [0.31031063, 0.67398292, 0.92524012, 0.62650584, 0.66342859,
        0.56430331, 0.54636776, 0.85952447, 0.85182051],
       [0.99623957, 0.87877931, 0.53834517, 0.49735132, 0.12237266,
        0.86849067, 0.47211013, 0.62040811, 0.42483624],
       [0.23365284, 0.24569283, 0.28705031, 0.01204527, 0.2694977 ,
        0.53651146, 0.75357893, 0.17590988, 0.78415752],
       [0.27688741, 0.41927871, 0.33325933, 0.03517933, 0.82839981,
        0.0324555 , 0.78959797, 0.21809466, 0.8765982 ],


In [59]:
np.random.random_sample(a.shape)

array([[0.37149197, 0.02593385, 0.18073518, 0.9887438 , 0.74734831,
        0.30301605],
       [0.39157701, 0.0111627 , 0.67436814, 0.62341513, 0.40149579,
        0.42358316]])

In [65]:
#Randome Integer values
np.random.randint(4,10,size=(3,3))#start point and size

array([[5, 8, 8],
       [5, 4, 8],
       [9, 8, 7]])

In [66]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
#Repeating arrays
arr=np.array([[1,2,3]])
r1=np.repeat(arr,9,axis=1)
print(r1)

[[1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3]]


In [77]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]= 9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#Be careful when copying arrays

In [80]:
a=np.array([1,2,3])
b=a
print(b)
b[0]=100
print(b)
print(a)#changed too because of same referencing

[1 2 3]
[100   2   3]
[100   2   3]


In [81]:
a=np.array([1,2,3])
b=a.copy()#Only copying
print(b)
b[0]=100
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


##Mathematics

In [82]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [83]:
a+2

array([3, 4, 5, 6])

In [84]:
a-2

array([-1,  0,  1,  2])

In [85]:
a*2

array([2, 4, 6, 8])

In [86]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [87]:
b= np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [88]:
a**2

array([ 1,  4,  9, 16])

In [91]:
#take the sin
np.sin(a)
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


####Linear Algebra

In [96]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [97]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [98]:
#Finding the determinant
c= np.identity(3)
np.linalg.det(c)

np.float64(1.0)

###Statistus

In [103]:
stats= np.array([[1,2,3],[4,5,6]])
stats
print(np.min(stats,axis=1))#axis=1 row wise and if axis=0 entire matrix
print(np.max(stats))
print(np.sum(stats))
print(np.sum(stats,axis=0))

[1 4]
6
21
[5 7 9]


###Reorganizing Arrays

In [107]:
before= np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after= before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [108]:
#Vertically stacking matrices
v1= np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [111]:
#Horizontal Stacks
np.hstack([v1,v2])
h1= np.ones((2,4))
h2= np.zeros((2,2))
print(np.hstack([h1,h2]))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


###Miscellaneous

In [116]:
filedata=np.genfromtxt('datanumpy.txt',delimiter=',')
print(filedata)
filedata= filedata.astype('int32')
print(filedata)

[[  1.  99.   3.   4.   5.   6.]
 [ 19.  21.   0. 900.   9.   3.]
 [ 31.  32.  33.  49.  33.  54.]]
[[  1  99   3   4   5   6]
 [ 19  21   0 900   9   3]
 [ 31  32  33  49  33  54]]


###Boolean Masking and Advanced Indexing

In [118]:
print(filedata>6)
print(filedata[filedata>60])

[[False  True False False False False]
 [ True  True False  True  True False]
 [ True  True  True  True  True  True]]
[ 99 900]


In [120]:
#You can index with a list in numPy
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,2,8]])

[2 3 9]


In [123]:
print(np.any(filedata>60,axis=0))
print(np.all(filedata>60,axis=0))

[False  True False  True False False]
[False False False False False False]


In [125]:
print((filedata>60) & (filedata<100))

[[False  True False False False False]
 [False False False False False False]
 [False False False False False False]]


In [126]:
print(~(filedata>60) & (filedata<100))

[[ True False  True  True  True  True]
 [ True  True  True False  True  True]
 [ True  True  True  True  True  True]]
